### ISSUE TITLE
Strange error caused the bridge to stop relaying messages

### ISSUE THREAD

**Issue by poVoq** [OpenTTD/dibridge#229]
I recently saw that dibridge stopped relaying messages in a channel and while a restart fixed that the logs have a strange error:

```
IRCBridge[1052527]: AttributeError: '_MissingSentinel' object has no attribute 'call_soon_threadsafe'
IRCBridge[1052527]: 2024-04-09 13:57:16 ERROR    [asyncio] Task exception was never retrieved
IRCBridge[1052527]: future: <Task finished name='Task-46858' coro=<IRCRelay._relay_mesage() done, defined at /dibridge/irc.py:1>
IRCBridge[1052527]: Traceback (most recent call last):
IRCBridge[1052527]:   File "/dibridge/irc.py", line 220, in _relay_mesage
IRCBridge[1052527]:     relay.DISCORD.send_message(irc_username, message)
IRCBridge[1052527]:   File "/dibridge/discord.py", line 187, in send_message
IRCBridge[1052527]:     asyncio.run_coroutine_threadsafe(self._send_message(irc_username, message), self.loop)
IRCBridge[1052527]:   File "/usr/lib64/python3.11/asyncio/tasks.py", line 936, in run_coroutine_threadsafe
IRCBridge[1052527]:     loop.call_soon_threadsafe(callback)
IRCBridge[1052527]:     ^^^^^^^^^^^^^^^^^^^^^^^^^
```
This repeated over and over in the log.

**Comment by TrueBrain** [comment]
Ah, no, I was misreading the backtrace, and misremembering what the code does :)

It appears that the Discord connection was closed. This also resets the `loop` variable (to a sentinel value). So that explains the issue there.

This might happen when there is a connection error, but I thought it self-restored. Clearly, it does not. But that is an easy thing to experiment with, as that should be reproduceable :D Will look into it further!

**Comment by poVoq** [comment]
The odd thing is that I run multiple dibridges in parallel and only one was affected, so this would speak against an connection issue.

**Comment by TrueBrain** [comment]
> The odd thing is that I run multiple dibridges in parallel on the same server and only one was affected, so this would speak against an connection issue.

Connection error is more than a connection issue on your side :) In this case, it seems to be the Discord-side.

In more detail, this happens if the Discord backend disconnect us with an error-code that the Discord library is not used to handle. Which means it is a bit undefined what one can do to recover.

One could argue that you can just reconnect to Discord and try again. But the docs suggest that these issues only happen when there is a configuration error on the bot side (wrong token, wrong shard, etc). So it is likely to happen again. But in this case it seems more likely that the Discord platform made a boo-boo, and booted the bot for the wrong reasons. But to differentiate between those scenarios is tricky.

Possibly a way to recover is to just let the whole bridge crash. If you are like me, it will just restart, and continue its operation. But that feels a bit meh. Need to think a bit more about this :)

**Comment by TrueBrain** [comment]
One more question for you: how far back do your logs go? It is likely there was a backtrace just before these errors you pasted started. It would be interesting to see that error, if possible?

**Comment by poVoq** [comment]
No, the bridged channel is pretty quiet, so I doubt is was a rate limit error.

Scrolling back in the logs I also see this right before:
```
IRCBridge[1052527]: 2024-04-07 19:11:44 ERROR    [asyncio] Task exception was never retrieved
IRCBridge[1052527]: future: <Task finished name='Task-46845' coro=<IRCRelay._relay_mesage() done, defined at /dibridge/irc.py:1>
IRCBridge[1052527]: Traceback (most recent call last):
IRCBridge[1052527]:   File "/dibridge/irc.py", line 220, in _relay_mesage
IRCBridge[1052527]:     relay.DISCORD.send_message(irc_username, message)
IRCBridge[1052527]:   File "/dibridge/discord.py", line 187, in send_message
IRCBridge[1052527]:     asyncio.run_coroutine_threadsafe(self._send_message(irc_username, message), self.loop)
IRCBridge[1052527]:   File "/usr/lib64/python3.11/asyncio/tasks.py", line 936, in run_coroutine_threadsafe
IRCBridge[1052527]:     loop.call_soon_threadsafe(callback)
IRCBridge[1052527]:     ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by poVoq** [comment]
Updated the above error log, sorry for the previous one I mistakenly thought was not the same.

**Comment by TrueBrain** [comment]
Thank you! So the root-cause was `Received fragmented control frame`. Which terminated the websocket to Discord, which is an event not handled by the Discord library, and this bridge simply does nothing with it, causing the other exceptions you see.

That is fixable :)

**Comment by TrueBrain** [comment]
Right, should be fixed, and not resurface again :) It now basically reconnects automatically in such events.

Thank you for the reports and additional information. Dibridge is now one step better than it was before :D
