### ISSUE TITLE
Feature request: option to force nicknames on IRC to have a certain postfix

### ISSUE THREAD

**Issue by poVoq** [OpenTTD/dibridge#78]
I noticed that on Discord side the bridge ends up tagging people with usernames like "normal" and "lot" just by typing these words in a chat.

Obviously this is mainly a result of people choosing common english words as usernames, but it is still a bit annoying.

So not sure if there is a way to avoid this, or maybe it could be changed that the bridge only explicitly tags people on the Discord side when "@" is put in front of the username?

**Comment by TrueBrain** [comment]
On IRC it is very uncommon to use `@` before referencing people, which is against the spirit of this bridge. As native as possible, the experience should be on both sides.

In that same spirit, IRC usernames are picked as close as possible to the Discord's username. And then yes, if you have a silly Discord name, you can expect silly results ofc :)

The up-side is that this only happens if you ever talked in a bridge channel, so you have that going for you.

As a possible solution I could see that the bridge always adds `[d]` to IRC usernames. That makes it very unlikely that the name is referenced by accident.

As with other feature-requests, I do not have time to implement this, but I leave it open as "good first issue" if someone is interested in picking it. Basically, add a new option, say, `--irc-nickname-postfix` (I am not sold on this name), that allows you to set a postfix that will always be added to nicknames. Or something similar. Be creative.
